### PR TITLE
make osc52 buffer bigger to cover more use cases

### PR DESCRIPTION
**Pull request by amosbird**
This patch is a workaround for issues like https://github.com/jwilm/alacritty/issues/1002 .

### CODE REVIEW

**Comment by Mic92** [comment]
Thanks! Finally I can copy files transparently to my clipboard!

**Comment by h-michael** [comment]
@jwilm Hi, how is going this pr?

**Comment by Mic92** [comment]
This patch is just a workaround. It would need some dynamic memory allocation I guess.

**Comment by chrisduerr** [comment]
Replaced by https://github.com/jwilm/vte/pull/33.

**Pull request closed without merging**
